name: Nix Flake Check

on:
  push:
    branches: ['main']

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v18
      with:
        install_url: https://nixos.org/nix/install
        extra_nix_config: |
          auto-optimise-store = true
          experimental-features = nix-command flakes
          access-tokens = ${{ secrets.GITHUB_TOKEN }}

    - name: Run Nix Flake Check
      run: nix flake check

    - name: Nix Flake Checker
      uses: DeterminateSystems/flake-checker-action@v5
      with:
        send-statistics: false # optional, default is true